---
title: 'Knockback Stacking part 2: stack harder'
author: sp99
date: '2020-06-03'
categories:
  - Mechanics
slug: knockback-stacking-part-2-stack-harder
lastmod: '2020-06-03T21:04:21-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
---
For a long (long) time this type of combo has been a staple of Mango's game vs Marth on FD:

<div style='position:relative; padding-bottom:calc(56.25% + 44px)'><iframe src='https://gfycat.com/ifr/spotlesswillinghatchetfish?autoplay=0' frameborder='0' scrolling='no' width='100%' height='100%'  style='position:absolute;top:0;left:0;' allowfullscreen></iframe></div><p>



The usual tips on how to do it go along the lines of:  
`instant double jump`  
`hit with soft dair, not hard`  
`fast fall when you hit them`  
While the advice seems to help, lots of people still have trouble with it.  
This is because they're ignoring how it works: it's all about stacking, baby.

In the previous post I explained how *knockback stacking* worked, and assumed readers had a general idea about how knockback behaves.
There's a specific (and intuitive) part of knockback's behavior that's relevant here. When you hit someone they don't go flying infinitely and die, right? That's cause kb decays with time and once they exit hitstun they can act (drift, double jump, do specials, whatever). For kb stacking combos, this means when you hit them matters a lot.  

To be more specific, for shine dair combos you want the right amount of upwards vertical knockback before hitting with dair. Do it too early (too much positive vertical knockback), and they won't fall down fast enough, do it too late, and they'll land before you even get close to the ground. An extreme example of this is hitting Marth with shine into dair at 0%, do it fast enough and Marth will go up when daired.  

With this idea in mind, troubleshooting combos becomes easier:  
Did they go down too slowly? Dair later.  
Did they go down too fast? Dair earlier.  

Take into account your jumps too, you don't want to delay your dair and then hit them as you rise, it's usually better to jump early and dair later (notice the first dair in the mango clip). If that still doesn't work, *then* try hitting them with the late hit of dair.

Since you have to decide on the fly based on their DI, percent and how much time you need to reach them, it's no wonder people mess up. Experience helps a lot, but understaing it should speed it up quite a bit.

To keep this brief, I'll leave more applications for another post, but this should at least give you a basic enough understanding to draw up other scenarios or realize in what instances you've been using kb stacking without realizing it.

One last thing, I promised excited Westballz in my last post, so here you go:

<div style='position:relative; padding-bottom:calc(50% + 44px)'><iframe src="https://clips.twitch.tv/embed?clip=MildSuaveBottleTheTarFu&autoplay=false" frameborder="0" autoplay="false" allowfullscreen="true" width='100%' height='100%' style='position:absolute;top:0;left:0;' ></iframe></div><p>


