---
title: Samus notes
author: sp
date: '2023-02-04'
slug: []
categories:
  - Matchup notes
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2023-02-04T15:36:16-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

### Short notes

-   Shoot low, Samus is not gonna be jumping around frequently and she can crouch PS easily just like Marth.
-   Shielding is very strong vs Samus due to her slow grab. Run up shield, shielding after attacks, etc. are all good options vs her.
-   Laser or aerial into shield deals with both cc dsmash/dtilt and upb OoS. Angling your shield slightly down forward will keep you safe from up shield pokes (if you angle too much she can nair your head).
-   Practice punishing dsmash and dtilt on block, it changes the risk reward massively in your favor.
-   Laser shine or low nair shine can catch upb Oos or leave a small enough gap to make them miss the window, which will leave them stuck in shield.
-   Dair into upair kills much earlier than bair or fsmash, but only work if they don't ASDI down.
-   DO NOT falling bair from platforms unless Samus is already past cc percent.

### Gfycats

Laser ftilt is useful but can be punished by cc walk (lots of Samus players won't do this!).

::: {style="position:relative; padding-bottom:calc(70.19% + 44px)"}
<iframe src="https://gfycat.com/ifr/magnificentfrequentantarcticgiantpetrel?autoplay=0" frameborder="0" scrolling="no" width="100%" height="95%" style="position:absolute;top:0;left:0;" allowfullscreen>

</iframe>
:::

<p>

When Samus is on ledge she only has one option: reel in. This simplifies reactions and makes it much easier to respond quickly. Good Samus players will grapple sweetspot and input wall jump upb in case you're still holding ledge when they reel in, which will catch ledgehop aerials or staying on ledge. In response Falco can wait and do ledge stand on reaction, which will keep her from grabbing ledge and avoid wall jump upb.

::: {style="position:relative; padding-bottom:calc(70.19% + 44px)"}
<iframe src="https://gfycat.com/ifr/thoseenlightenedkiwi?autoplay=0" frameborder="0" scrolling="no" width="100%" height="95%" style="position:absolute;top:0;left:0;" allowfullscreen>

</iframe>
:::

<p>

If Samus still has her double jump she can double jump after the wall jump and waveland on stage, which will just beat the wait-\>ledge stand concept. She can also do this without her dj but it's much harder.

::: {style="position:relative; padding-bottom:calc(70.19% + 44px)"}
<iframe src="https://gfycat.com/ifr/fineelastickiwi?autoplay=0" frameborder="0" scrolling="no" width="100%" height="95%" style="position:absolute;top:0;left:0;" allowfullscreen>

</iframe>
:::

<p>

Laser df5 dair (or j6 when closer) lets Falco stop forward movement from Samus, is safe from most OoS options and also lets you whiff punish wd back dsmash. Falco can also call out the wd back with a df6 dair (doing a long dash is a good idea here!) in case Samus keeps going for that.

::: {style="position:relative; padding-bottom:calc(70.19% + 44px)"}
<iframe src="https://gfycat.com/ifr/anysmoothflounder?autoplay=0" frameborder="0" scrolling="no" width="100%" height="95%" style="position:absolute;top:0;left:0;" allowfullscreen>

</iframe>
:::

### Defense

-   If you get thrown onto a platform, it's common for Samus to tech chase with dair. Tech rolling and going for a slide off will end the punish (DI away from the platform, ASDI down).

-   Double jump sweetspot and side b shortens to ledge are very useful vs Samus, she has a much easier time covering higher recoveries using missiles and uptilt.

-   If Samus shoot a homing missile while you're recovering, you can side b into it and then do another option.

-   on most stages, Samus is unable to actually follow up after hitting you with upb. On Yoshi's and Fountain she can upb to top plat and then tech chase with dsmash to cover most options.

### Other stuff

-   If Samus is using platforms to get missiles out, you can either shoot high lasers to catch her coming down, specifically j5 high laser into df6 high laser should make her unable to get down until the second laser goes past her. If she manages to get a missile out, laser into shine is very annoying to deal with, the laser will interrupt her movement and then the reflected missile will be in her face. If you shine without lasering first, you're probably getting daired by Samus.

-   Fair and upair are great at catching her falling down and will beat her falling nair pretty consistently.

-   Backflip is very useful to pressure Samus in the corner. Using laser, late bair and ff shield can make it really hard for Samus to push past you.
